language: scala
sudo: false
git:
  submodules: false
scala:
  - 2.11.8
before_install:
  - pip install --user codecov
script:
  - ./bin/testAll.sh
after_success:
  - codecov
jdk:
  - oraclejdk8
  - oraclejdk7
# The actual formatter (core+cli main projects) should work on Java 6 as well,
# only the surrounding projects (like readme) rely on Java 7 APIs through
# transitive dependencies.
notifications:
  email:
    - olafurpg@gmail.com
branches:
  only:
    - master
