language: scala
script:
  - sbt clean coverage test &&
    sbt coverageAggregate
after_success: "sbt coveralls"
scala:
  - 2.11.7
jdk:
  - oraclejdk7
notifications:
  email:
    - olafurpg@gmail.com
branches:
  only:
    - master
