language: scala
script:
  - sbt clean coverage test &&
    sbt coverageAggregate
after_success: "sbt coverageReport coveralls"
scala:
  - 2.11.7
jdk:
# couchdb-scala uses http4s which forces us to run on java 8 :(
  - oraclejdk8
notifications:
  email:
    - olafurpg@gmail.com
branches:
  only:
    - master
