language: scala
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.coursier"
git:
  submodules: false
scala:
- 2.11.8
before_install:
- pip install --user codecov
script:
- ./bin/testAll.sh
after_success:
- ./bin/travisPublish.sh
- codecov
notifications:
  email:
  - olafurpg@gmail.com
branches:
  only:
  - master
env:
  global:
  - DEPLOY_KEY: deploy_key
  - COMMIT_AUTHOR_EMAIL: olafurpg@gmail.com
  - secure: txOVrT6JwVgvpBibyLGWRvb28AluVs/Q1Kx5/9cNliwpeYSQ7zcQ0gV57umZ3L9BIvbQVZgB31kPY83mUnv0izrF1kN87KSYByY4GzHTfYO/EPunLgunrImMJL3SL026LMpGSnJn12A+KqZs2K4Vec/xjKarQrTMUfEmmeQLRgo6RpKyLu4Rty8DsQxriQb9ZMi4WbMHw75KZLuKKH2wUIWVbsMKpBX3veUfXqRqgTAigATt782YugRPadTsgQpUYp5g624Om5i+BAAgStrucS7LuxIolGRhfPUX6I/tBjgFypBJlKy5mSKRh0DPQSQDYEPcr060kflARCDhocKm2dk1AClLjD51TitwDyHJacoSs+7e2Ps6eDCw8lRKydiN/op/l+rt7Sapbwdo09ZR49KXfXFZy4XJXcxvqcOqeztfUPp1bG/Z1iJOXTaR1f/qCisdiJcjXIQfUIwO73SBnOdQfHQhGJUOpm6Ttyx5V/7UqLlEXEIaoc9jSpBoCrSNEU4zfWWbH7X+wOjW0upPmrwFWtFea1YJDrL1c/GRJB3hU6pO8fon31lZ7LCffEL4LxWsiOroxl99QQR05xIizS0AGnrvnOMxpInatrSVajR+tz4glj/3ln4sZLzMoi66P4r+DRUBgMF8fI1RqCmyfdcUCaj0Bn8i8DLCT4ChM5o=
