language: scala
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.coursier"
git:
  submodules: false
scala:
- 2.11.8
before_install:
- pip install --user codecov
script:
- "./bin/testAll.sh"
after_success:
- codecov
notifications:
  email:
  - olafurpg@gmail.com
branches:
  only:
  - master
env:
  global:
  - COMMIT_AUTHOR_EMAIL: olafurpg@gmail.com
