language: scala
sudo: false
scala:
  - 2.11.7
before_install:
  - pip install --user codecov
script:
  - sbt clean coverage test &&
    sbt coverageAggregate
after_success:
  - codecov
jdk:
# Need java 8 for http4s in tests.
  - oraclejdk8
notifications:
  email:
    - olafurpg@gmail.com
branches:
  only:
    - master
